services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=weather_analyzer'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3308:3306'
